data:
  datasets:
  - Sine
  - JShape
  - Angle
  - PShape
  dim: 3
  downsample: 5
  horizon_size: 20
  inference_horizon: 10
  manifold: Sphere
  mean: 0.0
  sample_points: 200
  scale_factor: 1.5
  std: 1.0
ema:
  decay: 0.999
  update: 5
  warmup: 1000
model:
  embed_dim: 24
  hidden_dim: 96
  num_layers: 6
scheduler:
  gamma: 0.5
  step: 100000
train:
  batch_size: 100
  device: cpu
  epochs: 300001
  inf_every: 10000
  inf_run_step: 0.05
  inf_runs_num: 3
  lr: 0.0001
  print_every: 10000
