train:
  lr : 2.0e-4
  epochs : 25001
  batch_size : 100
  inf_every : 5000
  print_every : 5000
  device : 'cpu'
  inf_runs_num : 3
  inf_run_step : 0.05

model:
  hidden_dim : 96
  num_layers : 6
  embed_dim : 24

data:
  dim : 3
  manifold_data: Sphere
  manifold_inference: None # None Euclidean
  type_inference: None #None s2_to_tang
  datasets: ["Sine"] # "PShape" "Sine" "JShape", "Angle", "PShape"]
  horizon_size : 8
  inference_horizon : 4
  scale_factor : 2.0
  downsample : 5
  sample_points : 300
  mean : 0.0
  std : 1.0

ema:
  warmup : 1000
  update : 5
  decay : 0.999

scheduler:
  step : 5000
  gamma : 0.5
