data:
  datasets:
  - Sine
  - JShape
  dim: 3
  downsample: 5
  horizon_size: 20
  inference_horizon: 10
  manifold_data: Sphere
  manifold_inference: None
  mean: 0.0
  sample_points: 200
  scale_factor: 2.0
  std: 1.0
  type_inference: None
ema:
  decay: 0.999
  update: 5
  warmup: 1000
model:
  embed_dim: 24
  hidden_dim: 96
  num_layers: 6
scheduler:
  gamma: 0.5
  step: 5000
train:
  batch_size: 100
  device: cpu
  epochs: 100001
  inf_every: 5000
  inf_run_step: 0.05
  inf_runs_num: 3
  lr: 0.0002
  print_every: 5000
