data:
  datasets:
  - Sine
  - JShape
  dim: 3
  downsample: 5
  horizon_size: 20
  inference_horizon: 10
  manifold: Sphere
  mean: 0.0
  sample_points: 200
  scale_factor: 4
  std: 2.5
ema:
  decay: 0.999
  update: 5
  warmup: 1000
model:
  embed_dim: 24
  hidden_dim: 96
  num_layers: 6
scheduler:
  gamma: 0.5
  step: 1000
train:
  batch_size: 12
  device: cpu
  epochs: 10001
  inf_every: 1000
  inf_run_step: 0.1
  inf_runs_num: 3
  lr: 0.001
  print_every: 500
